ALTER TABLE "Launch"
  ADD COLUMN IF NOT EXISTS "platformTonTreasury" TEXT,
  ADD COLUMN IF NOT EXISTS "platformTokenTreasury" TEXT,
  ADD COLUMN IF NOT EXISTS "platformTonFeeBps" INTEGER NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS "platformTokenFeeBps" INTEGER NOT NULL DEFAULT 100;
